engines:
  rubocop:
    enabled: true
    exclude_fingerprints:
    - 1deadbbb4a858ae5aeeff38fc78ad557
    - 10973ead6ddf385b4d4d7ec0f75236ae

  bundler-audit:
    enabled: true

  fixme:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
      - ruby

ratings:
  paths:
  - Gemfile.lock
  - "**.rb"

exclude_paths:
- spec/**/*
- lib/pure_validator/core_extensions/**/*
